'use client'

import { ScanSession, SEVERITY_BG, Severity, SEVERITY_COLORS } from '@/lib/scan-types'
import { FileText, Download, Copy, CheckCircle, Globe, Clock, User, Hash, Shield, AlertTriangle, ChevronRight } from 'lucide-react'
import { useState } from 'react'
import { cn } from '@/lib/utils'

interface ReportPanelProps {
  session: ScanSession | null
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mb-6">
      <h3 className="text-[10px] text-[#64748b] font-mono uppercase tracking-widest mb-3 flex items-center gap-2">
        <span className="w-4 h-px bg-[#1e2535]" />
        {title}
        <span className="flex-1 h-px bg-[#1e2535]" />
      </h3>
      {children}
    </div>
  )
}

function MetaRow({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-center justify-between py-2 border-b border-[#1e2535] last:border-0">
      <span className="text-xs text-[#64748b] font-mono">{label}</span>
      <span className="text-xs text-[#e2e8f0] font-mono">{value}</span>
    </div>
  )
}

export function ReportPanel({ session }: ReportPanelProps) {
  const [copied, setCopied] = useState(false)

  if (!session || session.status === 'idle') {
    return (
      <div className="bg-[#0f1117] border border-[#1e2535] rounded-xl p-10 flex flex-col items-center justify-center gap-3">
        <FileText className="w-10 h-10 text-[#1e2535]" />
        <p className="text-sm text-[#334155] font-mono">No scan report available</p>
        <p className="text-xs text-[#334155]">Run a scan to generate a report</p>
      </div>
    )
  }

  const allFindings = session.phases.flatMap(p => p.findings)
  const critical    = allFindings.filter(f => f.severity === 'CRITICAL')
  const high        = allFindings.filter(f => f.severity === 'HIGH')
  const medium      = allFindings.filter(f => f.severity === 'MEDIUM')
  const s           = session.summary

  const reportMd = `# Security Assessment Report

**Target**     : ${session.config.target}
**Scope URL**  : ${session.config.scopeUrl}
**Researcher** : ${session.config.researcher}
**Scan Mode**  : ${session.config.mode.toUpperCase()}
**Date**       : ${session.startedAt ? new Date(session.startedAt).toLocaleString() : 'Pending'}
**Session ID** : ${session.id}

---

## Asset Enumeration Summary

| Phase | Metric | Count |
|-------|--------|-------|
| Passive | Subdomains | ${s.subdomainsPassive} |
| DNS | Live hosts | ${s.subdomainsResolved} |
| HTTP | Live URLs | ${s.liveUrls} |
| Crawl | Unique endpoints | ${s.uniqueEndpoints} |
| JS | APIs discovered | ${s.discoveredEndpoints} |
| Cloud | Open buckets | ${s.openBuckets} |
| Cloud | Dangling CNAMEs | ${s.danglingCnames} |
| Overall | Risk Score | ${Math.min(100, s.riskScore)}/100 |

---

## Vulnerability Summary

${critical.length > 0 ? `### CRITICAL Findings (${critical.length})

${critical.map(f => `- **${f.title}**: ${f.description}`).join('\n')}

` : ''}
${high.length > 0 ? `### HIGH Findings (${high.length})

${high.map(f => `- **${f.title}**: ${f.description}`).join('\n')}

` : ''}
---
*Generated by ReconForge v4.0*`

  const handleCopy = () => {
    navigator.clipboard.writeText(reportMd)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleDownload = () => {
    const blob = new Blob([reportMd], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `recon_${session.config.target}_${new Date().toISOString().slice(0,10)}.md`
    a.click()
    URL.revokeObjectURL(url)
  }

  const riskScore = Math.min(100,
    critical.length * 25 + high.length * 12 + medium.length * 5 + s.openBuckets * 20 + s.subdoTakeovers * 15
  )

  const riskLabel = riskScore >= 75 ? 'CRITICAL' : riskScore >= 50 ? 'HIGH' : riskScore >= 25 ? 'MEDIUM' : 'LOW'
  const riskColor = riskScore >= 75 ? '#ff3b5c' : riskScore >= 50 ? '#ff6b35' : riskScore >= 25 ? '#f7b731' : '#45d48a'

  return (
    <div className="space-y-4">
      {/* Risk score header */}
      <div className="bg-[#0f1117] border border-[#1e2535] rounded-xl p-5 flex items-center gap-5">
        <div className="relative w-20 h-20 flex-shrink-0">
          <svg viewBox="0 0 80 80" className="w-full h-full -rotate-90">
            <circle cx="40" cy="40" r="32" fill="none" stroke="#1e2535" strokeWidth="6" />
            <circle
              cx="40" cy="40" r="32" fill="none"
              stroke={riskColor} strokeWidth="6"
              strokeLinecap="round"
              strokeDasharray={`${2 * Math.PI * 32}`}
              strokeDashoffset={`${2 * Math.PI * 32 * (1 - riskScore / 100)}`}
              style={{ transition: 'stroke-dashoffset 1s ease' }}
            />
          </svg>
          <div className="absolute inset-0 flex flex-col items-center justify-center">
            <span className="text-lg font-bold font-mono" style={{ color: riskColor }}>{riskScore}</span>
            <span className="text-[8px] text-[#64748b] font-mono">/ 100</span>
          </div>
        </div>

        <div className="flex-1">
          <p className="text-xs text-[#64748b] font-mono uppercase tracking-widest mb-1">Risk Score</p>
          <p className="text-2xl font-bold" style={{ color: riskColor }}>{riskLabel} RISK</p>
          <p className="text-xs text-[#64748b] mt-1">
            {critical.length} critical · {high.length} high · {medium.length} medium ·{' '}
            {s.openBuckets} open buckets · {s.subdoTakeovers} takeovers
          </p>
        </div>

        <div className="flex gap-2">
          <button
            onClick={handleCopy}
            className="flex items-center gap-2 px-3 py-2 text-xs font-medium bg-[#1c1f2e] text-[#e2e8f0] border border-[#1e2535] rounded-lg hover:border-[#2a3347] transition-all"
          >
            {copied ? <CheckCircle className="w-3.5 h-3.5 text-[#45d48a]" /> : <Copy className="w-3.5 h-3.5" />}
            {copied ? 'Copied!' : 'Copy MD'}
          </button>
          <button
            onClick={handleDownload}
            className="flex items-center gap-2 px-3 py-2 text-xs font-semibold bg-[#00d4aa] text-[#0a0b0f] rounded-lg hover:bg-[#00a884] transition-all"
          >
            <Download className="w-3.5 h-3.5" />
            Export
          </button>
        </div>
      </div>

      {/* Report body */}
      <div className="bg-[#0f1117] border border-[#1e2535] rounded-xl p-5">
        <Section title="Scan Metadata">
          <div className="bg-[#0a0b0f] rounded-lg px-4 py-1 divide-y divide-[#1e2535]">
            <MetaRow label="Target"      value={session.config.target} />
            <MetaRow label="Scope URL"   value={session.config.scopeUrl} />
            <MetaRow label="Researcher"  value={session.config.researcher} />
            <MetaRow label="Mode"        value={session.config.mode.toUpperCase()} />
            <MetaRow label="Rate Limit"  value={`${session.config.rateLimit} RPS`} />
            <MetaRow label="Started"     value={session.startedAt ? new Date(session.startedAt).toLocaleString() : 'Not started'} />
            <MetaRow label="Status"      value={session.status.toUpperCase()} />
            <MetaRow label="Session ID"  value={session.id.slice(0,18) + '...'} />
          </div>
        </Section>

        <Section title="Coverage Metrics">
          <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
            {[
              { l: 'Passive Subdomains',  v: s.subdomainsPassive || 0  },
              { l: 'Live Subdomains',     v: s.subdomainsResolved || 0 },
              { l: 'Live URLs',           v: s.liveUrls || 0           },
              { l: 'Unique Endpoints',    v: s.uniqueEndpoints || 0    },
              { l: 'JS Files',            v: s.jsFiles || 0            },
              { l: 'Discovered APIs',     v: s.discoveredEndpoints || 0 },
              { l: 'Missing Sec Headers', v: s.missingSecurityHeaders || 0 },
              { l: 'JWT Flaws',           v: s.jwtFlaws || 0           },
              { l: 'Takeovers',           v: s.subdoTakeovers || 0      },
            ].map(({ l, v }) => (
              <div key={l} className="bg-[#0a0b0f] border border-[#1e2535] rounded-lg p-3">
                <p className="text-xl font-bold font-mono text-white">{(v || 0).toLocaleString()}</p>
                <p className="text-[10px] text-[#64748b] mt-0.5">{l}</p>
              </div>
            ))}
          </div>
        </Section>

        <Section title="All Findings">
          <div className="space-y-2">
            {allFindings.length === 0 && (
              <p className="text-sm text-[#334155] font-mono text-center py-4">No findings — run a full scan</p>
            )}
            {allFindings.map(f => (
              <div key={f.id} className={cn(
                "flex items-start gap-3 p-3 rounded-lg border",
                f.severity === 'CRITICAL' ? "bg-[#ff3b5c]/5 border-[#ff3b5c]/15" :
                f.severity === 'HIGH'     ? "bg-[#ff6b35]/5 border-[#ff6b35]/15" :
                "bg-[#0a0b0f] border-[#1e2535]"
              )}>
                <span className={cn("px-2 py-0.5 text-[9px] font-mono rounded border uppercase flex-shrink-0 mt-0.5", SEVERITY_BG[f.severity as Severity])}>
                  {f.severity}
                </span>
                <div className="flex-1 min-w-0">
                  <p className="text-sm text-[#e2e8f0] font-medium">{f.title}</p>
                  <p className="text-xs text-[#64748b] mt-0.5 line-clamp-2">{f.description}</p>
                </div>
                {f.cveId && (
                  <span className="text-[9px] font-mono bg-[#ff3b5c]/10 text-[#ff3b5c] border border-[#ff3b5c]/20 px-1.5 py-0.5 rounded flex-shrink-0">
                    {f.cveId}
                  </span>
                )}
              </div>
            ))}
          </div>
        </Section>
      </div>
    </div>
  )
}
