/**
 * Export utilities for generating professional security reports
 * Supports JSON, Markdown, CSV, and HTML formats
 */

import { ScanSession, Finding } from './scan-types'

/**
 * Generate Markdown report
 */
export function generateMarkdownReport(session: ScanSession): string {
  const totalFindings = session.phases.reduce((sum, p) => sum + p.findings.length, 0)
  const critical = session.summary.criticalFindings
  const high = session.summary.highFindings

  let md = `# Security Assessment Report

**Target:** \`${session.config.target}\`  
**Scope:** \`${session.config.scopeUrl}\`  
**Scan Date:** ${new Date(session.startedAt).toLocaleString()}  
**Scan Mode:** ${session.config.mode.toUpperCase()}  
**Status:** ${session.status}

---

## Executive Summary

| Metric | Value |
|--------|-------|
| Total Findings | ${totalFindings} |
| Critical | ${critical} |
| High | ${high} |
| Medium | ${session.summary.mediumFindings} |
| Low | ${session.summary.lowFindings} |
| Info | ${session.summary.infoFindings} |
| Risk Score | ${session.summary.riskScore}/100 |

### Risk Assessment

**Overall Risk Level:** ${getRiskLevel(session.summary.riskScore)}

${critical > 0 ? `⚠️ **CRITICAL:** ${critical} critical vulnerabilities require immediate remediation.` : '✓ No critical vulnerabilities found.'}

${high > 0 ? `⚠️ **HIGH:** ${high} high-severity issues should be addressed within 30 days.` : ''}

---

## Discovery Summary

- **Passive Subdomains:** ${session.summary.subdomainsPassive}
- **Live Hosts:** ${session.summary.liveUrls}
- **Unique Endpoints:** ${session.summary.uniqueEndpoints}
- **JS Discovered APIs:** ${session.summary.discoveredEndpoints}
- **Technologies Identified:** ${session.summary.technologies.length}
- **Outdated Components:** ${session.summary.outdatedComponents.length}

---

## Findings by Severity

${generateFindingsBySection(session, 'CRITICAL')}

${generateFindingsBySection(session, 'HIGH')}

${generateFindingsBySection(session, 'MEDIUM')}

${generateFindingsBySection(session, 'LOW')}

${generateFindingsBySection(session, 'INFO')}

---

## Scanning Methodology

This assessment employed a comprehensive 15-phase attack surface mapping and vulnerability scanning pipeline:

1. **Passive Subdomain Enumeration** - OSINT data aggregation
2. **DNS Resolution & Mutation** - Active DNS probing
3. **HTTP Probing & Fingerprinting** - Technology stack identification
4. **Headless Crawling** - JavaScript-rendered endpoint discovery
5. **JS Analysis & Secret Extraction** - Source code analysis
6. **Parameter Discovery** - Endpoint parameter mining
7. **Directory Fuzzing** - Hidden resource enumeration
8. **Cloud Asset Hunting** - Misconfigured bucket detection
9. **Subdomain Takeover Detection** - Dangling DNS validation
10. **OAuth/JWT/OIDC Mapping** - Authentication surface mapping
11. **GraphQL & API Discovery** - API endpoint enumeration
12. **Nuclei Vulnerability Scanning** - Template-based detection
13. **CORS Analysis** - Cross-origin policy evaluation
14. **Report Generation** - Comprehensive findings aggregation
15. **Notifications** - Alert delivery

---

## Recommendations

### Immediate Actions (Critical Priority)

${generateRemediationSteps(session.phases.flatMap(p => p.findings).filter(f => f.severity === 'CRITICAL').slice(0, 5))}

### Short-term Actions (30 days)

${generateRemediationSteps(session.phases.flatMap(p => p.findings).filter(f => f.severity === 'HIGH').slice(0, 5))}

### Long-term Actions (90 days)

- Implement continuous security monitoring
- Establish vulnerability response SLAs
- Conduct security awareness training
- Implement security headers (CSP, HSTS, etc.)
- Enable Web Application Firewall (WAF)

---

## Tools & Techniques

**Reconnaissance:**
- Subfinder, crt.sh, AlienVault OTX, Wayback Machine, RapidDNS

**DNS & Resolution:**
- massdns, dnsgen, dig

**HTTP Probing:**
- httpx, wafw00f, gowitness

**Crawling:**
- Katana, gau, hakrawler, uro

**JavaScript Analysis:**
- mantra, TruffleHog, xnLinkFinder, gf

**Vulnerability Scanning:**
- Nuclei, burp-suite, sqlmap, xsstrike

**API Testing:**
- jwt.io, nuclei, burp-suite

---

## Disclaimer

This report contains findings from automated and manual security testing. These findings represent potential vulnerabilities and should be validated by qualified security professionals. False positives may occur. Use this report as part of a comprehensive security program, not as the sole basis for security decisions.

---

*Report generated by ReconForge Security Platform*
*Assessment completed on ${new Date(session.completedAt || new Date()).toLocaleString()}*
`

  return md
}

/**
 * Generate JSON report for machine processing
 */
export function generateJSONReport(session: ScanSession): string {
  const report = {
    metadata: {
      generatedAt: new Date().toISOString(),
      scanId: session.id,
      target: session.config.target,
      scope: session.config.scopeUrl,
      mode: session.config.mode,
      status: session.status,
      startTime: session.startedAt,
      endTime: session.completedAt,
    },
    summary: session.summary,
    findings: session.phases.flatMap(p =>
      p.findings.map(f => ({
        id: f.id,
        severity: f.severity,
        title: f.title,
        description: f.description,
        url: f.url,
        detectionMethod: f.detectionMethod,
        cwe: f.cwe,
        owasp: f.owasp,
        cvss: f.cvss,
        toolsUsed: f.toolsUsed,
        remediationSteps: f.remediationSteps,
        references: f.references,
        timestamp: f.timestamp,
      })),
    ),
    phases: session.phases.map(p => ({
      id: p.id,
      name: p.name,
      status: p.status,
      duration: p.duration,
      findingCount: p.findings.length,
      logCount: p.logs.length,
    })),
  }

  return JSON.stringify(report, null, 2)
}

/**
 * Generate CSV report (findings only)
 */
export function generateCSVReport(session: ScanSession): string {
  const findings = session.phases.flatMap(p => p.findings)

  const headers = [
    'Severity',
    'Title',
    'Description',
    'URL',
    'CWE',
    'OWASP',
    'CVSS Score',
    'Detection Method',
    'Tools',
    'Phase',
    'Timestamp',
  ]

  const rows = findings.map(f => [
    f.severity,
    `"${f.title.replace(/"/g, '""')}"`,
    `"${f.description.replace(/"/g, '""')}"`,
    f.url || '',
    f.cwe.join('; '),
    f.owasp.join('; '),
    f.cvss?.baseScore || '',
    `"${f.detectionMethod.replace(/"/g, '""')}"`,
    f.toolsUsed.join('; '),
    f.phase,
    f.timestamp,
  ])

  return [headers.join(','), ...rows.map(r => r.join(','))].join('\n')
}

/**
 * Helper: Get risk level text
 */
function getRiskLevel(score: number): string {
  if (score >= 80) return '🔴 CRITICAL'
  if (score >= 60) return '🟠 HIGH'
  if (score >= 40) return '🟡 MEDIUM'
  if (score >= 20) return '🟢 LOW'
  return '✓ MINIMAL'
}

/**
 * Helper: Generate findings section for markdown
 */
function generateFindingsBySection(session: ScanSession, severity: string): string {
  const findings = session.phases
    .flatMap(p => p.findings)
    .filter(f => f.severity === severity)

  if (findings.length === 0) return ''

  let section = `### ${severity} Severity (${findings.length})\n\n`

  findings.forEach((finding, idx) => {
    section += `#### ${idx + 1}. ${finding.title}\n\n`
    section += `**Status:** ${severity}\n`

    if (finding.cvss) {
      section += `**CVSS Score:** ${finding.cvss.baseScore}/10 (${finding.cvss.baseSeverity})\n`
      section += `**CVSS Vector:** \`${finding.cvss.vector}\`\n`
    }

    if (finding.url) section += `**URL:** \`${finding.url}\`\n`

    if (finding.cwe.length > 0) section += `**CWE:** ${finding.cwe.join(', ')}\n`

    section += `\n${finding.description}\n\n`

    section += `**Detection Method:**\n\n${finding.detectionMethod}\n\n`

    if (finding.remediationSteps.length > 0) {
      section += `**Remediation:**\n\n`
      finding.remediationSteps.forEach(step => {
        section += `- ${step}\n`
      })
      section += '\n'
    }

    if (finding.references.length > 0) {
      section += `**References:**\n\n`
      finding.references.forEach(ref => {
        section += `- [${ref}](${ref})\n`
      })
      section += '\n'
    }

    section += '---\n\n'
  })

  return section
}

/**
 * Helper: Generate remediation steps
 */
function generateRemediationSteps(findings: Finding[]): string {
  if (findings.length === 0) return 'No high-priority items at this level.'

  let steps = ''
  findings.forEach((finding, idx) => {
    steps += `\n**${idx + 1}. ${finding.title}**\n\n`
    if (finding.remediationSteps.length > 0) {
      finding.remediationSteps.slice(0, 2).forEach(step => {
        steps += `- ${step}\n`
      })
    }
  })

  return steps
}

/**
 * Download report as file
 */
export function downloadReport(
  filename: string,
  content: string,
  mimeType: string = 'text/plain',
): void {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

/**
 * Copy to clipboard
 */
export async function copyToClipboard(content: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(content)
    return true
  } catch (error) {
    console.error('Failed to copy to clipboard:', error)
    return false
  }
}
